name: Laravel

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # No decoding step needed here. We will pass the secret directly to the SSH action.

    - name: Push code to EC2
      run: |
        rsync -avz --exclude='.env' --exclude='storage/*' --exclude='node_modules' --exclude='vendor' -e "ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PEM_KEY }}" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/clicktabs_master/

    - name: SSH and Composer commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PEM_KEY }} # This is the base64-encoded PEM key
        script: |
          sudo cp -r /home/ubuntu/clicktabs_master/* /var/www/clicktabs_master/
          sudo chown -R www-data:www-data /var/www/clicktabs_master
          sudo chmod -R 775 /var/www/clicktabs_master/storage /var/www/clicktabs_master/bootstrap/cache
          sudo -u www-data composer update -d /var/www/clicktabs_master
          sudo -u www-data composer install -d /var/www/clicktabs_master --no-dev
          sudo systemctl restart nginx
          cd /var/www/clicktabs_master
          sudo -u www-data php artisan cache:clear
          sudo -u www-data php artisan config:clear
          sudo -u www-data php artisan view:clear
          sudo -u www-data php artisan route:clear
