# on: push
# name: 🚀 Deploy website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: 🚚 Get latest code
#       uses: actions/checkout@v2.3.2
    
#     - name: 📂 Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#         server: 3.210.72.15
#         username: clicktabs
#         password: ${{T3nKAdquSPIZamVQ}}
#         server-directory: /var/www/click-tabs/




on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 📂 Sync files
      uses: webitsbr/github-to-ftp@1.0.1
      with:
        server: ${{ secrets.3.210.72.15 }}
        server-dir: ${{ secrets./var/www/click-tabs/ }}
        username: ${{ secrets.clicktabs}}
        password: ${{ secrets.T3nKAdquSPIZamVQ }}